// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: healthcheck/healthcheck/chain.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Chain struct {
	ChainId         string                `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ConnectionId    string                `protobuf:"bytes,2,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	Status          *MonitoredChainStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UpdateInterval  uint64                `protobuf:"varint,4,opt,name=updateInterval,proto3" json:"updateInterval,omitempty"`
	TimeoutInterval uint64                `protobuf:"varint,5,opt,name=timeoutInterval,proto3" json:"timeoutInterval,omitempty"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24e1b453b69ac81, []int{0}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return m.Size()
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Chain) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *Chain) GetStatus() *MonitoredChainStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Chain) GetUpdateInterval() uint64 {
	if m != nil {
		return m.UpdateInterval
	}
	return 0
}

func (m *Chain) GetTimeoutInterval() uint64 {
	if m != nil {
		return m.TimeoutInterval
	}
	return 0
}

type MonitoredChainStatus struct {
	Status                 uint64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp              uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Block                  uint64 `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	HealthCheckBlockHeight uint64 `protobuf:"varint,4,opt,name=healthCheckBlockHeight,proto3" json:"healthCheckBlockHeight,omitempty"`
}

func (m *MonitoredChainStatus) Reset()         { *m = MonitoredChainStatus{} }
func (m *MonitoredChainStatus) String() string { return proto.CompactTextString(m) }
func (*MonitoredChainStatus) ProtoMessage()    {}
func (*MonitoredChainStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24e1b453b69ac81, []int{1}
}
func (m *MonitoredChainStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonitoredChainStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonitoredChainStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonitoredChainStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitoredChainStatus.Merge(m, src)
}
func (m *MonitoredChainStatus) XXX_Size() int {
	return m.Size()
}
func (m *MonitoredChainStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitoredChainStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MonitoredChainStatus proto.InternalMessageInfo

func (m *MonitoredChainStatus) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MonitoredChainStatus) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MonitoredChainStatus) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *MonitoredChainStatus) GetHealthCheckBlockHeight() uint64 {
	if m != nil {
		return m.HealthCheckBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Chain)(nil), "healthcheck.healthcheck.Chain")
	proto.RegisterType((*MonitoredChainStatus)(nil), "healthcheck.healthcheck.MonitoredChainStatus")
}

func init() {
	proto.RegisterFile("healthcheck/healthcheck/chain.proto", fileDescriptor_d24e1b453b69ac81)
}

var fileDescriptor_d24e1b453b69ac81 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xcc, 0x6a, 0x52, 0xe9, 0x53, 0x14, 0x96, 0x52, 0x73, 0x90, 0x35, 0x44, 0x90, 0x5c, 0x8c,
	0xa0, 0x20, 0x78, 0x6d, 0x11, 0xec, 0xc1, 0x4b, 0xbc, 0x79, 0xdb, 0x6e, 0x16, 0x13, 0x9a, 0x66,
	0x43, 0xf2, 0x22, 0xfa, 0x2f, 0x3c, 0xfb, 0x8b, 0x3c, 0xf6, 0xe8, 0x49, 0x24, 0xf9, 0x23, 0x92,
	0xed, 0x87, 0x69, 0xb1, 0xb7, 0x7d, 0x33, 0x6f, 0xf6, 0xcd, 0x30, 0x70, 0x16, 0x49, 0x9e, 0x60,
	0x24, 0x22, 0x29, 0x26, 0x97, 0xed, 0xb7, 0x88, 0x78, 0x9c, 0xfa, 0x59, 0xae, 0x50, 0xd1, 0xe3,
	0x16, 0xe1, 0xb7, 0xde, 0xee, 0x37, 0x01, 0x6b, 0xd8, 0x2c, 0x52, 0x1b, 0xf6, 0xb4, 0x62, 0x14,
	0xda, 0xc4, 0x21, 0x5e, 0x37, 0x58, 0x8e, 0xd4, 0x85, 0x03, 0xa1, 0xd2, 0x54, 0x0a, 0x8c, 0x55,
	0x43, 0xef, 0x68, 0x7a, 0x0d, 0xa3, 0x77, 0xd0, 0x29, 0x90, 0x63, 0x59, 0xd8, 0xbb, 0x0e, 0xf1,
	0xf6, 0xaf, 0x2e, 0xfc, 0x2d, 0x17, 0xfd, 0x07, 0x95, 0xc6, 0xa8, 0x72, 0x19, 0xea, 0xb3, 0x8f,
	0x5a, 0x14, 0x2c, 0xc4, 0xf4, 0x1c, 0x0e, 0xcb, 0x2c, 0xe4, 0x28, 0x47, 0x29, 0xca, 0xfc, 0x85,
	0x27, 0xb6, 0xe9, 0x10, 0xcf, 0x0c, 0x36, 0x50, 0xea, 0xc1, 0x11, 0xc6, 0x53, 0xa9, 0x4a, 0x5c,
	0x2d, 0x5a, 0x7a, 0x71, 0x13, 0x76, 0x3f, 0x08, 0xf4, 0xfe, 0x3b, 0x49, 0xfb, 0x2b, 0xc7, 0x44,
	0x2b, 0x97, 0x16, 0x4e, 0xa0, 0xdb, 0xfc, 0x51, 0x20, 0x9f, 0x66, 0x3a, 0xaa, 0x19, 0xfc, 0x01,
	0xb4, 0x07, 0xd6, 0x38, 0x51, 0x62, 0xa2, 0x63, 0x9a, 0xc1, 0x7c, 0xa0, 0x37, 0xd0, 0x9f, 0x47,
	0x1c, 0x36, 0x11, 0x07, 0x0d, 0x76, 0x2f, 0xe3, 0xe7, 0x08, 0x17, 0xf6, 0xb7, 0xb0, 0x83, 0xdb,
	0xcf, 0x8a, 0x91, 0x59, 0xc5, 0xc8, 0x4f, 0xc5, 0xc8, 0x7b, 0xcd, 0x8c, 0x59, 0xcd, 0x8c, 0xaf,
	0x9a, 0x19, 0x4f, 0xa7, 0xed, 0x26, 0x5f, 0xd7, 0x7a, 0xc5, 0xb7, 0x4c, 0x16, 0xe3, 0x8e, 0x2e,
	0xf6, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xf5, 0x3d, 0xaf, 0xff, 0x01, 0x00, 0x00,
}

func (m *Chain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutInterval != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.TimeoutInterval))
		i--
		dAtA[i] = 0x28
	}
	if m.UpdateInterval != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.UpdateInterval))
		i--
		dAtA[i] = 0x20
	}
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintChain(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintChain(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MonitoredChainStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonitoredChainStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonitoredChainStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HealthCheckBlockHeight != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.HealthCheckBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.Block != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x18
	}
	if m.Timestamp != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if m.Status != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintChain(dAtA []byte, offset int, v uint64) int {
	offset -= sovChain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Chain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	if m.UpdateInterval != 0 {
		n += 1 + sovChain(uint64(m.UpdateInterval))
	}
	if m.TimeoutInterval != 0 {
		n += 1 + sovChain(uint64(m.TimeoutInterval))
	}
	return n
}

func (m *MonitoredChainStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovChain(uint64(m.Status))
	}
	if m.Timestamp != 0 {
		n += 1 + sovChain(uint64(m.Timestamp))
	}
	if m.Block != 0 {
		n += 1 + sovChain(uint64(m.Block))
	}
	if m.HealthCheckBlockHeight != 0 {
		n += 1 + sovChain(uint64(m.HealthCheckBlockHeight))
	}
	return n
}

func sovChain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChain(x uint64) (n int) {
	return sovChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Chain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &MonitoredChainStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateInterval", wireType)
			}
			m.UpdateInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutInterval", wireType)
			}
			m.TimeoutInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonitoredChainStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonitoredChainStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonitoredChainStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HealthCheckBlockHeight", wireType)
			}
			m.HealthCheckBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HealthCheckBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChain = fmt.Errorf("proto: unexpected end of group")
)
